default:
  ecpmFloors:
    - 1000
    - 500
    - 300
    - 100
    - 50
    - 30
    - 10
    - 5
    - 3
    - 1
  placements:
    default:
      interstitial:
      rewarded:

apps:
  123456:
    adSources:
      meta:
        placements:
          default:
            interstitial:
              placementId: 
            rewarded:
              placementId: 
            rewardedInterstitial:
              placementId: 
      mintegral:
        appId:
        appKey: 
        placements:
          default:
            interstitial:
              placementId: 
              adUnitId:
            rewarded:
              placementId:
              adUnitId:
      pangle:
        appId:
        placements:
          default:
            interstitial:
              placementId:
            rewarded:
              placementId: 
      applovin:
        sdkKey:
      liftoff:
        appId:
        placements:
          default:
            interstitial:
              placementId:
            rewarded:
              placementId:
 